### ISSUE TITLE
A malicious? client will crash jocko

### ISSUE THREAD

**Issue by llonchj** [travisjeffery/jocko#41]
`curl localhost:9092`

produces:

```
panic: read tcp [::1]:9092->[::1]:52133: i/o timeout

goroutine 45 [running]:
github.com/travisjeffery/jocko/server.(*Server).handleRequest(0xc420017680, 0x18d45e0, 0xc42008a040)
	/Users/llonchj/go/src/github.com/travisjeffery/jocko/server/server.go:132 +0xee6
created by github.com/travisjeffery/jocko/server.(*Server).Start.func1
	/Users/llonchj/go/src/github.com/travisjeffery/jocko/server/server.go:75 +0x119
exit status 2```

**Comment by dgryski** [comment]
If we're talking about malicious / buggy clients, fuzzing any protocol parsers would also give some easy wins.

**Comment by llonchj** [comment]
@dgryski LOL that was my first try...
