### ISSUE TITLE
sarama example

### ISSUE THREAD

**Issue by gertcuykens** [travisjeffery/jocko#66]
Hi, the sarama example is working on its own but I don't understand how to make a test work that has jocko running on its own and then after successful start up of the service do the same example on it?

This is the code I use to split the example into two so I can use a already running Jocko service instead.
https://github.com/gertcuykens/jocko/commit/39077e6c150271234dca65f46da515dbfaf20656

The result I get is 

```
make run
rm -rf /tmp/jocko/*
jocko broker \
                --debug \
                --log-dir="/tmp/jocko" \
                --broker-addr=127.0.0.1:9092 \
                --raft-addr=127.0.0.1:9093 \
                --serf-addr=127.0.0.1:9094 \
                --http-addr=127.0.0.1:9095 \
                --id=1
2017/10/23 00:25:02 [INFO] serf: EventMemberJoin: jocko-001 127.0.0.1
2017-10-23 00:25:02 [INFO] jocko: adding peer: &{ID:1 Port:9092 IP:127.0.0.1 SerfPort:0 RaftPort:9093 Status:1 conn:<nil>}
2017/10/23 00:25:02 [INFO] raft: Node at 127.0.0.1:9093 [Leader] entering Leader state
2017-10-23 00:25:02 [INFO] jocko: cluster leadership acquired
2017/10/23 00:25:02 [DEBUG] raft: Node 127.0.0.1:9093 updated peer set (2): [127.0.0.1:9093]
2017-10-23 00:25:16 [DEBUG] jocko: request: correlation id [50390780], client id [cmd/createtopic], request size [59], key [19]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":0,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":1,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":2,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: response: correlation id [50390780], key [19]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":3,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: request: correlation id [0], client id [sarama], request size [20], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":4,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: response: correlation id [0], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: request: correlation id [1], client id [sarama], request size [32], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":5,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: response: correlation id [1], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: request: correlation id [2], client id [sarama], request size [32], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":6,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: response: correlation id [2], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: request: correlation id [3], client id [sarama], request size [32], key [3]
2017-10-23 00:25:16 [DEBUG] jocko: broker/apply cmd 0:
&{"topic":"test_topic","id":7,"replicas":[1],"isr":[1],"leader":1,"preferred_leader":1}
2017-10-23 00:25:16 [DEBUG] jocko: response: correlation id [3], key [3]

```

on the server but on the client it goes wrong?

```
% go test -v
=== RUN   TestSarama
--- FAIL: TestSarama (0.01s)
panic: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes. [recovered]
        panic: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.

goroutine 9 [running]:
testing.tRunner.func1(0xc4201c20f0)
        /usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:711 +0x2d2
panic(0x14e4640, 0x15eda9a)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/travisjeffery/jocko/examples/sarama.TestSarama(0xc4201c20f0)
        /Users/gert/go/src/github.com/travisjeffery/jocko/examples/sarama/sarama_test.go:63 +0xf5e
testing.tRunner(0xc4201c20f0, 0x15af308)
        /usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL    github.com/travisjeffery/jocko/examples/sarama  0.032s
%
```

**Comment by gertcuykens** [comment]
it works now, never mind
